### ISSUE TITLE
Requirements issue

### ISSUE THREAD

**Issue by wokkel** [VIB-PSB/MINI-EX#4]
Hi,
I'm quite new to python (and especially setting up environments on Linux). I think you have created a very usefull module and would like to run it on my own data. Therefore I've tried to set it up, but run into some trouble.
I'm running Python 3.8.10 and i've installed the requirements.txt with pip. Then trying to run one of the processes separately, it seems that there is a requirement for a higher pandas version as version 0.25.3 doesn't have StringDtype.
What am I doing wrong?
Thanks in advance.

Here's my stacktrace:

(miniex-env) harald@vm-harald-linux:~/python/miniex$ python3 bin/MINIEX_grnboostMultiprocess.py example/INPUTS/TF_list.txt example/INPUTS/"miniexExample_matrix.txt" 5 example/OUTPUTS/"miniexExample_grnboost2.txt"
Traceback (most recent call last):
  File "bin/MINIEX_grnboostMultiprocess.py", line 10, in <module>
    from arboreto.algo import grnboost2, _prepare_input
  File "/home/harald/python/miniex-env/lib/python3.8/site-packages/arboreto/algo.py", line 7, in <module>
    from arboreto.core import create_graph, SGBM_KWARGS, RF_KWARGS, EARLY_STOP_WINDOW_LENGTH
  File "/home/harald/python/miniex-env/lib/python3.8/site-packages/arboreto/core.py", line 11, in <module>
    from dask.dataframe import from_delayed
  File "/home/harald/python/miniex-env/lib/python3.8/site-packages/dask/dataframe/__init__.py", line 4, in <module>
    from dask.dataframe import backends, dispatch, rolling
  File "/home/harald/python/miniex-env/lib/python3.8/site-packages/dask/dataframe/backends.py", line 20, in <module>
    from dask.dataframe.core import DataFrame, Index, Scalar, Series, _Frame
  File "/home/harald/python/miniex-env/lib/python3.8/site-packages/dask/dataframe/core.py", line 35, in <module>
    from dask.dataframe import methods
  File "/home/harald/python/miniex-env/lib/python3.8/site-packages/dask/dataframe/methods.py", line 22, in <module>
    from dask.dataframe.utils import is_dataframe_like, is_index_like, is_series_like
  File "/home/harald/python/miniex-env/lib/python3.8/site-packages/dask/dataframe/utils.py", line 18, in <module>
    from dask.dataframe import (  # noqa: F401 register pandas extension types
  File "/home/harald/python/miniex-env/lib/python3.8/site-packages/dask/dataframe/_dtypes.py", line 16, in <module>
    @make_array_nonempty.register(pd.StringDtype)
  File "/home/harald/python/miniex-env/lib/python3.8/site-packages/pandas/__init__.py", line 214, in __getattr__
    raise AttributeError("module 'pandas' has no attribute '{}'".format(name))
AttributeError: module 'pandas' has no attribute 'StringDtype'

**Comment by caferra** [comment]
Hi, and sorry for the late reply!

To avoid these kind of issue we built a Docker container with all the necessary requirements - it gets downloaded automatically (as in the first block of the config file).

I hope it works!
